const sampleContacts = [
  {
    contactType: "trabajo",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@work.com",
    phone: "123-456-7890",
    notes: "Trabajo: Proyecto X",
  },
  {
    contactType: "personal",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en septiembre",
  },
  {
    contactType: "trabajo",
    firstName: "Juan",
    lastName: "Perez",
    email: "juan.perez@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en septiembre",
  },
  {
    contactType: "personal",
    firstName: "Pedro",
    lastName: "Gonzalez",
    email: "pedro.gonzalez@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Diciembre",
  },
  {
    contactType: "trabajo",
    firstName: "Maria",
    lastName: "Perez",
    email: "maria.perez@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Enero",
  },
  {
    contactType: "personal",
    firstName: "David",
    lastName: "Johnson",
    email: "david.johnson@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Marzo",
  },
  {
    contactType: "trabajo",
    firstName: "Laura",
    lastName: "Garcia",
    email: "laura.garcia@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Abril",
  },
  {
    contactType: "personal",
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Mayo",
  },
  {
    contactType: "trabajo",
    firstName: "Sophia",
    lastName: "Martinez",
    email: "sophia.martinez@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Junio",
  },
  {
    contactType: "personal",
    firstName: "Daniel",
    lastName: "Anderson",
    email: "daniel.anderson@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Julio",
  },
  {
    contactType: "trabajo",
    firstName: "Olivia",
    lastName: "Lopez",
    email: "olivia.lopez@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Agosto",
  },
  {
    contactType: "personal",
    firstName: "James",
    lastName: "Lee",
    email: "james.lee@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Octubre",
  },
  {
    contactType: "trabajo",
    firstName: "Emma",
    lastName: "Harris",
    email: "emma.harris@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Noviembre",
  },
  {
    contactType: "personal",
    firstName: "William",
    lastName: "Clark",
    email: "william.clark@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Enero",
  },
  {
    contactType: "trabajo",
    firstName: "Ava",
    lastName: "Young",
    email: "ava.young@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Febrero",
  },
  {
    contactType: "personal",
    firstName: "Joseph",
    lastName: "Walker",
    email: "joseph.walker@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Marzo",
  },
  {
    contactType: "trabajo",
    firstName: "Mia",
    lastName: "Hall",
    email: "mia.hall@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Abril",
  },
  {
    contactType: "personal",
    firstName: "Benjamin",
    lastName: "Lewis",
    email: "benjamin.lewis@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Mayo",
  },
  {
    contactType: "trabajo",
    firstName: "Charlotte",
    lastName: "King",
    email: "charlotte.king@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Junio",
  },
];

export default sampleContacts;
