const sampleContacts = [
  {
    contactType: "trabajo",
    firstName: "John",
    lastName: "Doe",
    id: "John-Doe-trabajo",
    email: "john.doe@work.com",
    phone: "123-456-7890",
    notes: "Trabajo: Proyecto X",
  },
  {
    contactType: "personal",
    firstName: "Jane",
    lastName: "Smith",
    id: "Jane-Smith-personal",
    email: "jane.smith@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en septiembre",
  },
  {
    contactType: "trabajo",
    firstName: "Juan",
    lastName: "Perez",
    id: "Juan-Perez-trabajo",
    email: "juan.perez@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en septiembre",
  },
  {
    contactType: "personal",
    firstName: "Pedro",
    lastName: "Gonzalez",
    id: "Pedro-Gonzalez-personal",
    email: "pedro.gonzalez@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Diciembre",
  },
  {
    contactType: "trabajo",
    firstName: "Maria",
    lastName: "Perez",
    id: "Maria-Perez-trabajo",
    email: "maria.perez@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Enero",
  },
  {
    contactType: "personal",
    firstName: "David",
    lastName: "Johnson",
    id: "David-Johnson-personal",
    email: "david.johnson@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Marzo",
  },
  {
    contactType: "trabajo",
    firstName: "Laura",
    lastName: "Garcia",
    id: "Laura-Garcia-trabajo",
    email: "laura.garcia@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Abril",
  },
  {
    contactType: "personal",
    firstName: "Michael",
    lastName: "Brown",
    id: "Michael-Brown-personal",
    email: "michael.brown@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Mayo",
  },
  {
    contactType: "trabajo",
    firstName: "Sophia",
    lastName: "Martinez",
    id: "Sophia-Martinez-trabajo",
    email: "sophia.martinez@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Junio",
  },
  {
    contactType: "personal",
    firstName: "Daniel",
    lastName: "Anderson",
    id: "Daniel-Anderson-personal",
    email: "daniel.anderson@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Julio",
  },
  {
    contactType: "trabajo",
    firstName: "Olivia",
    lastName: "Lopez",
    id: "Olivia-Lopez-trabajo",
    email: "olivia.lopez@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Agosto",
  },
  {
    contactType: "personal",
    firstName: "James",
    lastName: "Lee",
    id: "James-Lee-personal",
    email: "james.lee@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Octubre",
  },
  {
    contactType: "trabajo",
    firstName: "Emma",
    lastName: "Harris",
    id: "Emma-Harris-trabajo",
    email: "emma.harris@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Noviembre",
  },
  {
    contactType: "personal",
    firstName: "William",
    lastName: "Clark",
    id: "William-Clark-personal",
    email: "william.clark@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Enero",
  },
  {
    contactType: "trabajo",
    firstName: "Ava",
    lastName: "Young",
    id: "Ava-Young-trabajo",
    email: "ava.young@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Febrero",
  },
  {
    contactType: "personal",
    firstName: "Joseph",
    lastName: "Walker",
    id: "Joseph-Walker-personal",
    email: "joseph.walker@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Marzo",
  },
  {
    contactType: "trabajo",
    firstName: "Mia",
    lastName: "Hall",
    id: "Mia-Hall-trabajo",
    email: "mia.hall@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Abril",
  },
  {
    contactType: "personal",
    firstName: "Benjamin",
    lastName: "Lewis",
    id: "Benjamin-Lewis-personal",
    email: "benjamin.lewis@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Mayo",
  },
  {
    contactType: "trabajo",
    firstName: "Charlotte",
    lastName: "King",
    id: "Charlotte-King-trabajo",
    email: "charlotte.king@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Junio",
  },
  {
    contactType: "personal",
    firstName: "Elijah",
    lastName: "Baker",
    id: "Elijah-Baker-personal",
    email: "asjkhdfkljh@gmail.com",
    phone: "987-654-3210",
    notes: "Cumpleaños en Julio",
  },
];

export default sampleContacts;
